### PR TITLE
Compiler/0.12

### PR DESCRIPTION
**Pull request by kRITZCREEK**

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Fixes #36, @newlandsvalley Could you check if I got all the combinators that should return NELs in 19bc664?

**Comment by newlandsvalley** [comment]
OK - I'll take a look.

**Comment by newlandsvalley** [comment]
As far as I can tell, only sepBy1 is missing.  Also, I think that the doc comments on endBy and endBy1 should be swapped over.

**Comment by kRITZCREEK** [comment]
Good catch! Thanks :)

**Comment by newlandsvalley** [comment]
Many thanks for fixing this, @kRITZCREEK .

**Comment by kRITZCREEK** [comment]
You're welcome :) Thanks for taking a look

**Pull request merged**
