### PR TITLE
Update according to Contributors library guidelines

### PR DESCRIPTION
**Pull request by JordanMartinez**
This pull request is part of an effort to update and standardize the Contributors libraries according to the [Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md). Specifically, it:

1. Adjusts the files and repository structure according to the [repository structure](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#repository-structure) section of the guidelines, which includes standard pr templates, issue templates, CI in GitHub Actions, automatic stale issue management, ensures the project uses Spago, and so on.
2. Updates the README and documentation according to the [documentation](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#documentation) section of the guidelines. This is a first step towards ensuring Contributors libraries have adequate module documentation, READMEs, a docs directory, and tests (even if just usage examples) in a `test` directory.
3. Updates labels where relevant to help folks better sift through issues on this library and get started contributing.

This PR is the groundwork for followup efforts to ensure contributor libraries are kept up-to-date, documented, tested, and accessible to users and new contributors.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@JordanMartinez It looks like some extra files are still in here (the Travis file, the backups directory). Mind removing those?

**Comment by JordanMartinez** [comment]
Done. Sorry, I missed that part in the instructions.

**Comment by thomashoneyman** [comment]
Sorry, one last thing! In the `.github` directory I see:

Screen Shot 2020-09-13 at 11 39 35 AM

and we should remove the `issue_template.md` file (it's replaced by the ISSUE_TEMPLATE directory), and the `contributing.md` and `pull_request_template.md` files (we only need the capitalized `CONTRIBUTING.md` and `PULL_REQUEST_TEMPLATE.md` files).

Otherwise this is good to go!

**Comment by JordanMartinez** [comment]
Fixed!
I think I reverted my commits and reran the contrib tool. Looks like I forgot to do the `git mv` step.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
