### PR TITLE
fix alternative instance to satisfy parse (bc <|> bd) bd

### LINKED ISSUE #15: Strange error using alphaNum
Getting a strange error using `alphaNum`:

    > import Text.Parsing.StringParser
    > import Text.Parsing.StringParser.String 
    > runParser alphaNum "A"
    Left (Expected a lower case character but found 'A')

Attached my bower_components folder so you can see what dependencies I have installed, renamed to a .zip because Github being a diva:

[bower_components.tar.gz.zip](https://github.com/paf31/purescript-string-parsers/files/101952/bower_components.tar.gz.zip)

Great library, good API btw

### PR DESCRIPTION
**Pull request by ssadler**
Fixes #15 

Changes behaviour to match Attoparsec:

``` haskell
import Control.Applicative
import Data.Attoparsec.Text
main = print $ parse ("bc" <|> "bd") "bd"
```

### CODE REVIEW

**Comment by paf31** [comment]
I don't know if matching Attoparsec is a good thing though. The quality of the error messages could suffer.

**Comment by libscott** [comment]
Right. I suppose the other option would be to provide `try`:
```haskell
alphaNum = try anyLetter <|> anyDigit <?> "Expected a letter or a number"
```
So that shared prefixes are explicitly permitted.  Assuming this would work, I would prefer it, then it becomes explicit and optional.

**Comment by paf31** [comment]
Yes, `try` is the way to go right now:

https://github.com/paf31/purescript-string-parsers/blob/260a27d97203a048ced6189ff9e631198445cb74/src/Text/Parsing/StringParser.purs#L89

I'm pretty sure the instances are correct. Maybe `anyLetter` is too eager to consume input in case of failure.

**Comment by libscott** [comment]
I updated the code to use `try` in order to fix `alphaNum`. is used in String.md. I think it's a bit inconsistent though, since now the necessity of `try` depends on the implementation of the parser and not the intention; see [`string`](https://github.com/libscott/purescript-string-parsers/blob/b28b768ab645f6205b00f360921babbbfc21cfd9/src/Text/Parsing/StringParser/String.purs#L54) for example, the implementation doesn't increase the position (though it legitimately could) so it works.

```haskell
parseTest (string "am" <|> string "pm") "pm"
-- "pm"

parseTest (lowerCaseChar <|> upperCaseChar) "U" 
-- "Expected a lower case character but found 'U'"

parseTest (try lowerCaseChar <|> upperCaseChar) "U" 
-- 'U'
```

I'd say the question is, what is the utility of the `pos` variable in the failure case?

In the case that we want to branch between 2 parsers that do not accept any common prefix, and therefore we would like the parser to fail if the first parser is able to advance at all, then what should `string` pass if it fails? It needs to pass the number of characters that it did match.

**Comment by libscott** [comment]
So I drafted a change for that. It's a bit subtle though. I'm not sure if Expr.purs needs a change too, since I'm not sure how it works.

**Comment by libscott** [comment]
I was wrong, and this is still not fixed:

```haskell
> runParser (lowerCaseChar <|> char '!') "!"
Left (Expected a lower case character but found '!')

> runParser (string "abc" <|> string "def") "def"
Right ("def")
```

At this point I think that the Attoparsec behaviour is making more sense, otherwise either every parser has to report how many characters they matched successfully which looks difficult to get right.

I vote for merging 05d5777.

**Comment by paf31** [comment]
The issue here is not in `<|>`, or in `alphaNum`, it is in `lowerCaseChar` and `upperCaseChar`. Both should be using `satisfy` with `<?>` to provide a better error message.

**Comment by hdgarrood** [comment]
For future reference this was fixed at some point; this is what I see now:

```
> runParser (lowerCaseChar <|> char '!') "!"
(Right '!')

> runParser (string "abc" <|> string "def") "def"
(Right "def")
```

**Pull request closed without merging**
